### PR TITLE
fix(repeat): handle container sizing change

### LINKED ISSUE #21: Dimensions for scroll, etc calculated once on attached(). Needs to be dynamic.
itemHeight, virtualScrollHeight, etc are all calculated from the size of the scroll view when attached() is called in virtual-repeat.js. There are a few problems with this:
1. It doesn't resize.
2. If the element is hidden (display none), then this.virtualScrollHeight remains as -2.

Needs to be a hook for resize and display to recalculate these values.

### LINKED ISSUE #69: Recalculate Items Shown on Resize
In the event that your scroll container is dynamic in size, and you resize that container to be larger than the initial buffer size, you will notice that you now have a blank space below the items that is not being filled in. When you scroll, you'll see the items being rebound and scrolling appropriately, but the space below remains empty.

### LINKED ISSUE #114: Bottom placeholder height not updated when getter changed with computedFrom
**I'm submitting a bug report**

* **Library Version:**
1.0.0-beta.3.1.0

**Please tell us about your environment:**
* **Operating System:**
Ubuntu 17.10

* **Node Version:**
8.4.0

* **NPM Version:**
5.3.0

* **Browser:**
all

* **Language:**
all

**Current behavior:**
virtual-repeat has to iterate over the return value of a getter annotated with computedFrom. The source objects changes and the getter evaluates new which results in a new array instance which get's bound to the custom attribute.

**Expected/desired behavior:**
When the attribute gets a new array instance from outside it should update the placeholder heights.

**How to fix:**
Currently the ArrayRepeatStrategy.itemsChanged is called on attached lifecycle instead of the bind: https://github.com/aurelia/ui-virtualization/blob/master/src/virtual-repeat.js#L90
Actually it has to be called on both (attached and bind) since bind will be called before the element is attached and you can calculate the height only when it's attached. But bind can be called after attachment as well :)
You could easily optimize the the initial redundancy by check if the element already is attached.
As well the check in the calculation has to be extended that it permits the case when views are there but no items
https://github.com/aurelia/ui-virtualization/blob/master/src/virtual-repeat.js#L457

Previous
```js
if (this._viewsLength > 0 && this._itemsLength === itemsLength || itemsLength <= 0) {
  return;
}
```

After
```js
if (this._viewsLength > 0 && this._itemsLength === itemsLength || this._viewsLength <= 0 && itemsLength <= 0) {
  return;
}
```

### PR DESCRIPTION
**Pull request by bigopon**
This PR adds fixes related to container resize handler using `ResizeObserver` https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

This has pretty poor browser supports (only Chrome), but fortunately it's polyfill-able (though not 100% match native capability). Polyfill at https://github.com/que-etc/resize-observer-polyfill

To support browsers without official support for `ResizeObserver` seamlessly, without enforcing a polyfill, adds event based APIs:

```html
<div ref="containerEl">
  <div virtual-repeat.for="item of items">${item}</div>
</div>
```
```js
import { VirtualizationEvents } from 'aurelia-ui-virtualization'

...
containerEl.dispatchEvent(new CustomEvent(VirtualizationEvents.scrollerSizeChange, { bubbles: true })
```

or can use string: `virtual-repeat-scroller-size-changed`

demo at https://dist-dgzkyqywpr.now.sh/#/issue-21-69 works natively in browsers with `ResizeObserver`, needs some event dispatching for browsers withour `ResizeObserver`.

cc @EisenbergEffect @AStoker 

closes #21
closes #69
closes #114

### CODE REVIEW

File: src/interfaces.ts [hunk 1]
```diff
@@ -151,6 +151,24 @@ export interface IScrollerInfo {
   height: number;
 }
 
+export const enum VirtualizationCalculation {
+  none              = 0b0_00000,
+  reset             = 0b0_00001,
+  has_sizing        = 0b0_00010,
+  observe_scroller  = 0b0_00100
```
Comment (EisenbergEffect) [inline src/interfaces.ts:158]: Somebody's been reading @fkleuver's code a lot 🤣

**Comment by EisenbergEffect** [comment]
@bigopon As always, thanks for working so hard on the vCurrent libraries to keep them healthy for the community. Just want to double check: is this ready to do or do you have some last additions to make?

**Comment by bigopon** [comment]
@EisenbergEffect Yes it is ready to go. Could always use more tests but I think existing 500/600 integration tests should suffice for now. I have more plan for this, so maybe lets go for the next beta.
