### PR TITLE
fix(virtual-repeat): make initially hidden elements display correctly

### LINKED ISSUE #73: Items don't render when initially hidden
**I'm submitting a bug report**
- **Library Version:**
  1.0.0-beta.1.0.2

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.9|iOS|Windows 10
- **Node Version:**
  5.5.0
  
  
- **NPM Version:**
  3.3.2
  
  
- **JSPM OR Webpack AND Version**
  JSPM 0.16.39
  
  
- **Browser:**
  all
- **Language:**
  ESNext

**Current behavior:**
When page loads, the virtual repeat element is contained inside a div that is hidden. Later, when that div is revealed, the virtual repeat elements do not show except for the first one (this is due to how the element heights are calculated).

**Expected/desired behavior:**

- **What is the expected behavior?**
  The expected behavior is that the elements will show appropriately, despite being hidden initially.
- **What is the motivation / use case for changing the behavior?**
  Motivation/use case for this scenario is in the event of a mobile first design, where certain panels are hidden on mobile, and the panels are revealed depending on where you navigate to (where as on desktop all the panels are visible). 

What probably needs to happen to resolve this is figure out a different way to calculate the initial heights of elements. Currently, it depends on those elements being visible and their heights being calculate-able when everything is initialized. When this isn't the case, or when views change size, the calculate heights function is not fired again, and therefore nothing changes in the view.

### PR DESCRIPTION
**Pull request by AStoker**
fixes: https://github.com/aurelia/ui-virtualization/issues/73
Previous behavior was that any `virtual-repeat` that was initially
hidden could not correctly calculate heights. New behavior is such that
initially hidden elements can display correctly after they have been
shown.

### CODE REVIEW

File: src/virtual-repeat.js [hunk 1]
```diff
@@ -411,7 +411,14 @@ export class VirtualRepeat extends AbstractRepeater {
     let firstViewElement = this.view(0).lastChild;
     this.itemHeight = calcOuterHeight(firstViewElement);
     if (this.itemHeight <= 0) {
-      throw new Error('Could not calculate item height');
+      this._sizeInterval = setInterval(()=>{
```
Comment (martingust) [inline src/virtual-repeat.js:417]: `this._sizeInterval` might need to be terminated in the detached callback as well. In case the item height never gets greater than 0.

Comment (AStoker) [reply src/virtual-repeat.js:417]: Ohh, good call. Do you think 500ms is fine for the interval? I just made it match the interval (time wise) with the one defined earlier in regards to scrolling. Possibly make it faster, slower?

**Comment by AStoker** [comment]
Any other notes @martingust?

**Comment by martingust** [comment]
@AStoker I think it's all good. I'll get this merged later today.

**Comment by AStoker** [comment]
@martingust, any idea on when this will get published to a new release?

**Comment by martingust** [comment]
@EisenbergEffect Can you release this repo? There is a breaking change waiting in master https://github.com/aurelia/ui-virtualization/commit/b7ff55551e469c9bfc6f07eacd0284adf7fbc0f0
